version = "0.1.0"
last_updated = "2025-10-03T14:42:59.325"

[compile]
emit_ir = true
parallel = true
flags = ["-std=c++17", "-fPIC", "-O2"]
enabled = true
output_dir = "build/ir"

[link]
optimize = true
opt_level = "O2"
enabled = true
output_dir = "build/linked"
lto = false

[binary]
library_type = "shared"
library_name = "libsimple_math.so"
rpath = true
enabled = true
output_dir = "julia"

[workflow]
stages = ["discovery", "compile", "link", "binary", "symbols", "wrap"]
parallel_stages = ["compile"]
stop_on_error = true

[target]
features = []
cpu = "generic"
triple = ""

[symbols]
filter_internal = true
method = "nm"
demangle = true
enabled = true

[cache]
enabled = true
invalidate_on_change = true
directory = ".jmake_cache"

[wrap]
add_docs = true
module_name = "Simple_math"
add_tests = true
style = "auto"
enabled = true
output_dir = "julia"

[reorganize]
enabled = false

[project]
name = "simple_math"
root = "/home/grim/.julia/julia/JMake/examples/simple_math"

[llvm]
root = "/home/grim/.julia/julia/JMake/LLVM"
use_jmake_llvm = true
isolated = true

    [llvm.tools]
    llvm_link = "/home/grim/.julia/julia/JMake/LLVM/tools/llvm-link"
    opt = "/home/grim/.julia/julia/JMake/LLVM/tools/opt"
    llvm_ar = "/home/grim/.julia/julia/JMake/LLVM/tools/llvm-ar"
    llvm_config = "/home/grim/.julia/julia/JMake/LLVM/tools/llvm-config"
    llvm_nm = "/home/grim/.julia/julia/JMake/LLVM/tools/llvm-nm"
    clang = "/home/grim/.julia/julia/JMake/LLVM/tools/clang++"
    llc = "/home/grim/.julia/julia/JMake/LLVM/tools/llc"

[test]
enabled = false

[discovery]
dependency_graph_file = ".jmake_cache/dependency_graph.json"
include_dirs = ["/home/grim/.julia/julia/JMake/examples/simple_math", "/home/grim/.julia/julia/JMake/examples/simple_math/include", "/home/grim/.julia/julia/JMake/examples/simple_math/src"]
enabled = true
completed = true
timestamp = "2025-10-03T14:42:59.325"

    [discovery.files]
    cpp_sources = ["src/math_ops.cpp"]
    total_scanned = 3
    cpp_headers = []
    c_sources = []
    c_headers = ["include/math_ops.h"]

    [discovery.binaries]
    static_libs = []
    shared_libs = []
    total = 0
    executables = []
